### ISSUE TITLE
Levels = Warning leads to a successful run??

### ISSUE THREAD

**Issue by zhilothebest** [AtlasWHHV/Gen_Reco#8]
`EVNTtoDAOD 14:58:16 Summarizing all message counts
EVNTtoDAOD 14:58:16 =====================================================
EVNTtoDAOD 14:58:16  Message Source              |   Level |    Count
EVNTtoDAOD 14:58:16 -----------------------------+---------+-------------
EVNTtoDAOD 14:58:16  AthenaPoolCnvSvc            | WARNING |        2
EVNTtoDAOD 14:58:16  ChronoAuditor               | WARNING |        1
EVNTtoDAOD 14:58:16  HistogramPersistencySvc     | WARNING |        1
EVNTtoDAOD 14:58:16  InputMetaDataStore          | WARNING |       20
EVNTtoDAOD 14:58:16  PoolSvc                     | WARNING |        1
EVNTtoDAOD 14:58:16  ToolSvc.FileMetaDataCreatorTool| WARNING |        3
EVNTtoDAOD 14:58:16  ToolSvc.jblda               | WARNING |        3
EVNTtoDAOD 14:58:16  xAODMaker::EventInfoCnvAlg.EventInfoCnvTool| WARNING |        2
EVNTtoDAOD 14:58:16 =====================================================
EVNTtoDAOD 14:58:16 Py:Athena            INFO leaving with code 0: "successful run"
`

How are we having a successful run when all of the level's are warnings? You should be able to run the shell script in any folder and it should work now.

**Comment by ghost** [comment]
Half of me wants to simply point out that physicists wrote this, and we only have access to the three files given to us.  Without being able to dig into the files that are being used (i e. The entirety of MadGraph and the like), we're kinda s.o.l.  I have gotten these responses after running sets of events in MadGraph and using the Generate_tf.py bit.  I'm 96.3% sure that's what you are suppose to see.  Bloody physicists...

**Comment by zhilothebest** [comment]
I guess as long as the Root file reads right?

**Comment by gordonwatts** [comment]
In general... WARNINGS in this code can be ignored. That half that says "phycisists wrote this" is the correct half, I'm afraid. Basically, they are there because the author of the code decided that this might be an indication that their code can't handle something further down, so rather than protect and fail if they really are in that situation, the warning is issued. In isolation this is fine, but with 1000's and 1000's of these... well... So... 

Of course, sometimes there are real warnings. This is why we will keep log files around. If we see a problem with one of the plots we might go back and look at the warnings. So, good for now. Ignore. :-)
